sonar.projectKey=todo-app
sonar.projectName=TodoApp

sonar.language=php
sonar.sourceEncoding=UTF-8

sonar.php.coverage.reportPaths=coverage/clover.xml
sonar.php.tests.reportPaths=tests/.phpunit.result.cache

sonar.exclusions=vendor/**,node_modules/**,bootstrap/**,resources/**,routes/**,storage/**,coverage/**

sonar.sources=app

sonar.host.url=http://localhost:9000